app/app.py
from flask import Flask
from app.user_manager import login_manager


def create_app(config_filename):

    app = Flask(__name__)
    app.config.from_pyfile(config_filename)
    login_manager.init_app(app)
    login_manager.session_protection = "strong"

    from app.controllers.chat_controller import chat_controller
    from app.controllers.login_controller import login_controller
    from app.controllers.registration_controller import registration_controller

    app.register_blueprint(chat_controller)
    app.register_blueprint(login_controller)
    app.register_blueprint(registration_controller)

    login_manager.login_view = '/login'
    return app

app/controllers/chat_controller.py
from flask import Blueprint
from flask import jsonify
from flask import render_template
from flask import request
from flask_login import login_required, current_user
from werkzeug.exceptions import ServiceUnavailable
from app.services.messages_service import MessagesService

chat_controller = Blueprint('chat_controller', __name__)


@chat_controller.route('/', methods=['GET', ])
@login_required
def index():
    nick = current_user.nick
    service = MessagesService()
    result = service.receive(nick)
    if result is None:
        result = []
    return render_template('index.html', messages=result)


@chat_controller.route('/send', methods=['POST', ])
@login_required
def send():
    nick = current_user.nick
    data = request.get_json()
    message = data['message']
    service = MessagesService()
    if service.send(nick, message):
        return '', 200
    else:
        return ServiceUnavailable()


# Запрос не является идеомпотентным, поэтому используем метод POST
@chat_controller.route('/receive', methods=['POST', ])
@login_required
def receive():
    nick = current_user.nick
    service = MessagesService()
    result = service.receive(nick)
    return jsonify(result)

app/controllers/login_controller.py
from datetime import timedelta
from flask import Blueprint
from flask import current_app
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for
from flask_login import login_user, logout_user, login_required, current_user
from app.user import User
from app.services.user_service import UserService

login_controller = Blueprint('login_controller', __name__)


@login_controller.route('/login', methods=['GET', ])
def index():

    if current_user.is_authenticated:
        return redirect(url_for('chat_controller.index'))

    return render_template('login.html')


@login_controller.route('/login', methods=['POST'], )
def login():

    nick = request.form['nick']
    password = request.form['password']

    service = UserService()
    is_authorized = service.authorize(nick, password)
    if is_authorized:
        session.permanent = True
        lifetime = current_app.config['SESSION_LIFETIME']
        current_app.permanent_session_lifetime = timedelta(minutes=lifetime)
        login_user(User(nick), remember=True)
        session['user'] = nick
        session.new = True
        return redirect(url_for('chat_controller.index'))
    else:
        return render_template('login.html', error=True)


@login_controller.route('/login', methods=['DELETE', ])
@login_required
def logout():
    print(current_user.nick)
    session.clear()
    logout_user()

    return index()

app/controllers/registration_controller.py
from flask import Blueprint
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from app.services.user_service import UserService

registration_controller = Blueprint('registration_controller', __name__)


@registration_controller.route('/register', methods=['GET', ])
def index():

    if current_user.is_authenticated:
        return redirect(url_for('chat_controller.index'))

    return render_template('registration.html')


@registration_controller.route('/register', methods=['POST', ])
def register():
    nick = request.form['nick']
    password = request.form['password']

    service = UserService()
    result = service.register(nick, password)
    if result:
        return redirect(url_for('login_controller.index'))
    else:
        return render_template('registration.html', error=True)

app/templates/index.html
<style>
    div {
        margin: 20px;
    }
    div.c-input-area {
        min-height: 100px;
    }
    div.c-messages {
        border: 1px solid black;
        height: 80%;
    }
    input.c-message-input {
        width: 80%;
    }
    p {
        margin: 10px
    }
</style>

<html>
    <head>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
        <script>
            function send() {
                var message = $("input#message-input")[0].value;
                var data = { message: message };
                $.ajax({
                    type: 'POST',
                    url: '/send',
                    data: JSON.stringify(data),
                    contentType: 'application/json; charset=UTF-8'
                });

                $("input#message-input")[0].value = '';
                receive();
            }

            function receive() {
                var request = $.ajax({
                    type: 'POST',
                    url: '/receive',
                    dataType: 'application/json'
                });
                
                request.always(appendNewMessages);
            }

            function appendNewMessages(data){
                if (data.status == 200) {
                    messages = $.parseJSON(data.responseText);
                    $.each(messages, function(i ,message) {
                        var messageElement = '<p class="c-message">' + message + "</p>"
                        $('div.c-messages').append(messageElement)
                    });
                }
            }

            function logout() {
                var request = $.ajax({
                    type: "DELETE",
                    url: "{{url_for('login_controller.logout')}}",
                });
                request.always(function (){
                    window.location.href = "{{url_for('login_controller.index')}}";
                })
            }

            $(document).ready(function() {
                window.setInterval(receive, 3000);
            });

        </script>
    </head>
    <body>
        <div>
            <input type="button" value="Выход" onclick="logout()"/>
        </div>
        <div class="c-messages">
            {% for message in messages %}
            <p class="c-message" >{{message}}</p>
            {% endfor %}
        </div>
        <div>
            <input id="message-input" class="c-message-input" type="text" />
            <input type="button" value="Отправить" onclick="send()"/>
        </div>
    </body>
</html>

app/templates/login.html
<html>
    <body>
        <form name="login" action="/login" method="POST">
            <label for="input-nick" >Ник</label>
            <input type="text" name="nick" id="input-nick" />
            <label for="input-password">Пароль</label>
            <input type="password" name="password" id="input-password" />
            <button type="submit">Вход</button>
        </form name="login">
        <div>
            <a href="{{url_for('registration_controller.index')}}">Регистрация</a>
        </div>
        <div>
            {% if error %}
            <p>Вы не можете быть авторизованы. Попробуйте другой ник или пароль</p>
            {% endif %}
        </div>
    </body>
</html>

app/templates/registration.html
<html>
    <body>
        <form name="login" action="/register" method="POST">
            <label for="input-nick" >Ник</label>
            <input type="text" name="nick" id="input-nick" />
            <label for="input-password">Пароль</label>
            <input type="password" name="password" id="input-password" />
            <button type="submit">Зарегистрироваться</button>
        </form name="login">
        <div>
            {% if error %}
            <p>Ник уже занят, пожалуйста, выберите другой</p>
            {% endif %}
        </div>
    </body>
</html>